export default {
	"app": {
		"name": "SucreCloud"
	},
	"auth": {
		"isLogin": true
	},
	"explorer": {
		"namecomponent": "explorer",
		"renameDialog": {
			"status": "ready",
			"errorMsg": "",
			"cantEdit": false,
			"open": false,
			"name": ""
		},
		"moveOrCopyDialog": {
			"op": "copy",
			"pathSelectedToMoveOrCopy": "",
			"path": "",
			"open": false,
			"name": "",
			"fetchingPath": false,
			"paths": {},
			"stauts": "ok",
			"errorMsg": "",
			"currentPath": "/"
		},
		"toolBar": {
			"filter": ""
		},
		"selection": {
			"isSelecteMode": true,
			"selecteds": {}
		},
		"currentType": "folder",
		"paths": {
			"/David/Clase magistral de proyecto, profe miguel": {
				"status": "ok",
				"path": "/David/Clase magistral de proyecto, profe miguel",
				"file": false,
				"data": [{
					"size": 278428,
					"path": "/David/Clase magistral de proyecto, profe miguel/Estructura del PNFI.pdf",
					"modificationTime": 1531708033733,
					"name": "Estructura del PNFI.pdf",
					"replication": 3,
					"accessTime": 1531708033653,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1025056,
					"path": "/David/Clase magistral de proyecto, profe miguel/Informacion sobre el pnfi.pdf",
					"modificationTime": 1531708033873,
					"name": "Informacion sobre el pnfi.pdf",
					"replication": 3,
					"accessTime": 1531708033751,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 13652,
					"path": "/David/Clase magistral de proyecto, profe miguel/PNF informatica.docx",
					"modificationTime": 1531708033941,
					"name": "PNF informatica.docx",
					"replication": 3,
					"accessTime": 1531708033917,
					"mime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 370793,
					"path": "/David/Clase magistral de proyecto, profe miguel/solicitud de aprobacion del proyecto sociotecnologico PNFI.pdf",
					"modificationTime": 1531708034045,
					"name": "solicitud de aprobacion del proyecto sociotecnologico PNFI.pdf",
					"replication": 3,
					"accessTime": 1531708033966,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}],
				"size": 1687929,
				"directoryCount": 1,
				"fileCount": 4,
				"time": 129
			},
			"/David": {
				"status": "ok",
				"path": "/David",
				"file": false,
				"data": [{
					"size": 4548787,
					"path": "/David/04 Psychosocial.mp3",
					"modificationTime": 1531708033572,
					"name": "04 Psychosocial.mp3",
					"replication": 3,
					"accessTime": 1531708033354,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 107928138,
					"path": "/David/Arch Enemy - Will To Power [Full Album].mp4",
					"modificationTime": 1531831761636,
					"name": "Arch Enemy - Will To Power [Full Album].mp4",
					"replication": 3,
					"accessTime": 1531831756949,
					"mime": "video/mp4",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4,
					"path": "/David/Clase magistral de proyecto, profe miguel",
					"modificationTime": 1531837122290,
					"name": "Clase magistral de proyecto, profe miguel",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 4,
					"file": false
				}, {
					"size": 222548,
					"path": "/David/Manejo del mouse en lenguaje C++.zip",
					"modificationTime": 1531796876081,
					"name": "Manejo del mouse en lenguaje C++.zip",
					"replication": 3,
					"accessTime": 1531796875742,
					"mime": "application/zip",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 3,
					"path": "/David/coordinador",
					"modificationTime": 1531708034649,
					"name": "coordinador",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 3,
					"file": false
				}, {
					"size": 22,
					"path": "/David/darknet master",
					"modificationTime": 1531839385673,
					"name": "darknet master",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 22,
					"file": false
				}, {
					"size": 0,
					"path": "/David/david2ascac",
					"modificationTime": 1531708131681,
					"name": "david2ascac",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 0,
					"file": false
				}, {
					"size": 7,
					"path": "/David/demo",
					"modificationTime": 1531708132135,
					"name": "demo",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 7,
					"file": false
				}, {
					"size": 1,
					"path": "/David/electiva modulo 2",
					"modificationTime": 1531708132336,
					"name": "electiva modulo 2",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 1,
					"file": false
				}, {
					"size": 13,
					"path": "/David/hazelcast-jetty9-sessionmanager-1.0.2-javadoc",
					"modificationTime": 1531708134069,
					"name": "hazelcast-jetty9-sessionmanager-1.0.2-javadoc",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 13,
					"file": false
				}, {
					"size": 46182803,
					"path": "/David/logo SucreCloud.png",
					"modificationTime": 1531708136097,
					"name": "logo SucreCloud.png",
					"replication": 3,
					"accessTime": 1531708134145,
					"mime": "image/png",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1,
					"path": "/David/nueva carpeta",
					"modificationTime": 1531708136321,
					"name": "nueva carpeta",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 1,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi",
					"modificationTime": 1531708599993,
					"name": "openfire_src.orchi",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 23033908,
					"path": "/David/vlc-record-2017-12-28-21h22m49s-david@orchi ~_spark_spark-2.0.0-bin-hadoop2.7-.avi",
					"modificationTime": 1531708666716,
					"name": "vlc-record-2017-12-28-21h22m49s-david@orchi ~_spark_spark-2.0.0-bin-hadoop2.7-.avi",
					"replication": 3,
					"accessTime": 1531708665358,
					"mime": "video/x-msvideo",
					"persission": "rw-r--r--",
					"file": true
				}],
				"size": 577581817,
				"directoryCount": 1029,
				"fileCount": 5862,
				"time": 284
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/AdminProvider.java": {
				"status": "error",
				"error": "connection_error",
				"errorMsg": "error de coneccion"
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerListener.java": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerListener.java",
				"file": true,
				"data": {
					"size": 1495,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerListener.java",
					"modificationTime": 1531708177403,
					"name": "XMPPServerListener.java",
					"fileBase64Content": "LyoqCiAqICRSQ1NmaWxlOiAkCiAqICRSZXZpc2lvbjogJAogKiAkRGF0ZTogJAogKgogKiBDb3B5cmlnaHQgKEMpIDIwMDUtMjAwOCBKaXZlIFNvZnR3YXJlLiBBbGwgcmlnaHRzIHJlc2VydmVkLgogKgogKiBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKICogeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgogKiBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKICoKICogICAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMAogKgogKiBVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlCiAqIGRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCiAqIFdJVEhPVVQgV0FSUkFOVElFUyBPUiBDT05ESVRJT05TIE9GIEFOWSBLSU5ELCBlaXRoZXIgZXhwcmVzcyBvciBpbXBsaWVkLgogKiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kCiAqIGxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgogKi8KCnBhY2thZ2Ugb3JnLmppdmVzb2Z0d2FyZS5vcGVuZmlyZTsKCi8qKgogKiBJbnRlcmZhY2UgdGhhdCBsZXQgb2JzZXJ2ZXJzIGJlIG5vdGlmaWVkIHdoZW4gdGhlIHNlcnZlciBoYXMgYmVlbiBzdGFydGVkIG9yIGlzCiAqIGFib3V0IHRvIGJlIHN0b3BwZWQuIFVzZSB7QGxpbmsgWE1QUFNlcnZlciNhZGRTZXJ2ZXJMaXN0ZW5lcihYTVBQU2VydmVyTGlzdGVuZXIpfSB0bwogKiBhZGQgbmV3IGxpc3RlbmVycy4KICoKICogQGF1dGhvciBHYXN0b24gRG9tYmlhawogKi8KcHVibGljIGludGVyZmFjZSBYTVBQU2VydmVyTGlzdGVuZXIgewoKICAgIC8qKgogICAgICogTm90aWZpY2F0aW9uIG1lc3NhZ2UgaW5kaWNhdGluZyB0aGF0IHRoZSBzZXJ2ZXIgaGFzIGJlZW4gc3RhcnRlZC4gQXQgdGhpcyBwb2ludAogICAgICogYWxsIHNlcnZlciBtb2R1bGVzIGhhdmUgYmVlbiBpbml0aWFsaXplZCBhbmQgc3RhcnRlZC4gTWVzc2FnZSBzZW5kaW5nIGFuZCByZWNlaXZpbmcKICAgICAqIGlzIG5vdyBwb3NzaWJsZS4gSG93ZXZlciwgc29tZSBwbHVnaW5zIG1heSBzdGlsbCBiZSBwZW5kaW5nIHRvIGJlIGxvYWRlZC4KICAgICAqLwogICAgdm9pZCBzZXJ2ZXJTdGFydGVkKCk7CgogICAgLyoqCiAgICAgKiBOb3RpZmljYXRpb24gbWVzc2FnZSBpbmRpY2F0aW9uIHRoYXQgdGhlIHNlcnZlciBpcyBhYm91dCB0byBiZSBzdG9wcGVkLiBBdCB0aGlzIHBvaW50CiAgICAgKiBhbGwgbW9kdWxlcyBhcmUgc3RpbGwgcnVubmluZyBzbyBhbGwgc2VydmljZXMgYXJlIHN0aWxsIGF2YWlsYWJsZS4KICAgICAqLwogICAgdm9pZCBzZXJ2ZXJTdG9wcGluZygpOwp9Cg==",
					"accessTime": 1531708177380,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				},
				"time": 71
			},
			"/": {
				"status": "ok",
				"path": "/",
				"file": false,
				"data": [{
					"size": 142975,
					"path": "/32-CGI.pdf",
					"modificationTime": 1531841685236,
					"name": "32-CGI.pdf",
					"replication": 3,
					"accessTime": 1531841684671,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 3193104,
					"path": "/A Day To Remember - Since U Been Gone [HQ].mp3",
					"modificationTime": 1531277619912,
					"name": "A Day To Remember - Since U Been Gone [HQ].mp3",
					"replication": 3,
					"accessTime": 1531277619335,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 7017463,
					"path": "/ACDC Thunderstruck.mp3",
					"modificationTime": 1531277619525,
					"name": "ACDC Thunderstruck.mp3",
					"replication": 3,
					"accessTime": 1531277618532,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1428056,
					"path": "/ANÁLISIS DE ARQUITECTURAS DE procesado de streaming de big data.pdf",
					"modificationTime": 1531778212485,
					"name": "ANÁLISIS DE ARQUITECTURAS DE procesado de streaming de big data.pdf",
					"replication": 3,
					"accessTime": 1531778212279,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 5934740,
					"path": "/Adashore - Waves (feat. Wade Walters).mp3",
					"modificationTime": 1531277620796,
					"name": "Adashore - Waves (feat. Wade Walters).mp3",
					"replication": 3,
					"accessTime": 1531277619299,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 9460017,
					"path": "/Alter Bridge - Cry of Achilles (Official Video).mp3",
					"modificationTime": 1531277620805,
					"name": "Alter Bridge - Cry of Achilles (Official Video).mp3",
					"replication": 3,
					"accessTime": 1531277619628,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 6137868,
					"path": "/Alter Bridge - Isolation GMV.mp3",
					"modificationTime": 1531277620796,
					"name": "Alter Bridge - Isolation GMV.mp3",
					"replication": 3,
					"accessTime": 1531277619658,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4924133,
					"path": "/Alter Bridge - Show Me A Leader.mp3",
					"modificationTime": 1531277621107,
					"name": "Alter Bridge - Show Me A Leader.mp3",
					"replication": 3,
					"accessTime": 1531277619835,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 7037157,
					"path": "/Alter Bridge - Slip to the Void Music Video.mp3",
					"modificationTime": 1531277622248,
					"name": "Alter Bridge - Slip to the Void Music Video.mp3",
					"replication": 3,
					"accessTime": 1531277620869,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 7060722,
					"path": "/Alter bridge -Metalingus 1.mp3",
					"modificationTime": 1531277621093,
					"name": "Alter bridge -Metalingus 1.mp3",
					"replication": 3,
					"accessTime": 1531277619758,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 107928138,
					"path": "/Arch Enemy - Will To Power [Full Album].mp4",
					"modificationTime": 1531711679000,
					"name": "Arch Enemy - Will To Power [Full Album].mp4",
					"replication": 3,
					"accessTime": 1531711674178,
					"mime": "video/mp4",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 17646220,
					"path": "/Architects - 'Gravity'.mp4",
					"modificationTime": 1531277623331,
					"name": "Architects - 'Gravity'.mp4",
					"replication": 3,
					"accessTime": 1531277620969,
					"mime": "video/mp4",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4466802,
					"path": "/Asking alexandria-the black.m4a",
					"modificationTime": 1531277622226,
					"name": "Asking alexandria-the black.m4a",
					"replication": 3,
					"accessTime": 1531277621163,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 121467,
					"path": "/DRPC.png",
					"modificationTime": 1531665071905,
					"name": "DRPC.png",
					"replication": 3,
					"accessTime": 1531665071822,
					"mime": "image/png",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 14,
					"path": "/David",
					"modificationTime": 1531851980446,
					"name": "David",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 14,
					"file": false
				}, {
					"size": 4304699,
					"path": "/Dead Memories.mp3",
					"modificationTime": 1531277619211,
					"name": "Dead Memories.mp3",
					"replication": 3,
					"accessTime": 1531277618433,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 6091706,
					"path": "/Dirtyphonics DIRTY.mp4",
					"modificationTime": 1531519699105,
					"name": "Dirtyphonics DIRTY.mp4",
					"replication": 3,
					"accessTime": 1531519698119,
					"mime": "video/mp4",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 12227,
					"path": "/Esquema de red orchi.odg",
					"modificationTime": 1531363826222,
					"name": "Esquema de red orchi.odg",
					"replication": 3,
					"accessTime": 1531363826109,
					"mime": "application/vnd.oasis.opendocument.graphics",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 11406,
					"path": "/Esquema de red orchi.pdf",
					"modificationTime": 1531363826225,
					"name": "Esquema de red orchi.pdf",
					"replication": 3,
					"accessTime": 1531363826110,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 278428,
					"path": "/Estructura del PNFI.pdf",
					"modificationTime": 1531837047395,
					"name": "Estructura del PNFI.pdf",
					"replication": 3,
					"accessTime": 1531837046884,
					"mime": "application/pdf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 6046,
					"path": "/Example.java",
					"modificationTime": 1531367914580,
					"name": "Example.java",
					"replication": 3,
					"accessTime": 1531367913818,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"replication": 3,
					"path": "/LICENSE.gpl",
					"file": true,
					"size": 35141,
					"modificationTime": 1531767189296,
					"name": "LICENSE.gpl",
					"persission": "rw-r--r--",
					"accessTime": 1531767189150
				}, {
					"size": 8562816,
					"path": "/Maniacal Me.mp3",
					"modificationTime": 1531277619661,
					"name": "Maniacal Me.mp3",
					"replication": 3,
					"accessTime": 1531277618486,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 178705,
					"path": "/O.xcf",
					"modificationTime": 1531363826191,
					"name": "O.xcf",
					"replication": 3,
					"accessTime": 1531363826108,
					"mime": "application/x-xcf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 255350,
					"path": "/ORCHi.xcf",
					"modificationTime": 1531363826071,
					"name": "ORCHi.xcf",
					"replication": 3,
					"accessTime": 1531363825998,
					"mime": "application/x-xcf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4337738,
					"path": "/Of Mice & Men - Bones Exposed.mp3",
					"modificationTime": 1531334030853,
					"name": "Of Mice & Men - Bones Exposed.mp3",
					"replication": 3,
					"accessTime": 1531334029935,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4548787,
					"path": "/Psychosocial.mp3",
					"modificationTime": 1531277619214,
					"name": "Psychosocial.mp3",
					"replication": 3,
					"accessTime": 1531277618353,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 7435555,
					"path": "/Run.m4a",
					"modificationTime": 1531277744333,
					"name": "Run.m4a",
					"replication": 3,
					"accessTime": 1531277744053,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 39257,
					"path": "/Sin nombre.xcf",
					"modificationTime": 1531363826220,
					"name": "Sin nombre.xcf",
					"replication": 3,
					"accessTime": 1531363826108,
					"mime": "application/x-xcf",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4,
					"path": "/Universidad",
					"modificationTime": 1531835202034,
					"name": "Universidad",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 4,
					"file": false
				}, {
					"size": 8415117,
					"path": "/Weight Of The World.mp3",
					"modificationTime": 1531277619655,
					"name": "Weight Of The World.mp3",
					"replication": 3,
					"accessTime": 1531277618561,
					"mime": "audio/mpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 10688540,
					"path": "/Zeds Dead x Charlotte OC - Symphony.mp4",
					"modificationTime": 1531450918173,
					"name": "Zeds Dead x Charlotte OC - Symphony.mp4",
					"replication": 3,
					"accessTime": 1531450915281,
					"mime": "video/mp4",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 32,
					"path": "/apache spark, ml, java, matematica, streaming, casos de estudio, conceptos",
					"modificationTime": 1531796955475,
					"name": "apache spark, ml, java, matematica, streaming, casos de estudio, conceptos",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 32,
					"file": false
				}, {
					"size": 3580,
					"path": "/contraportada.html",
					"modificationTime": 1531840120833,
					"name": "contraportada.html",
					"replication": 3,
					"accessTime": 1531840120710,
					"mime": "text/html",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 18532,
					"path": "/darknet.h",
					"modificationTime": 1531838970266,
					"name": "darknet.h",
					"replication": 3,
					"accessTime": 1531838969352,
					"mime": "text/x-chdr",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 2863627,
					"path": "/driveState3.json",
					"modificationTime": 1531363292217,
					"name": "driveState3.json",
					"replication": 3,
					"accessTime": 1531363292142,
					"mime": "application/json",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 26030,
					"path": "/hardrockcock_624266.jpg",
					"modificationTime": 1531798453996,
					"name": "hardrockcock_624266.jpg",
					"replication": 3,
					"accessTime": 1531798452753,
					"mime": "image/jpeg",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"replication": 3,
					"path": "/log.log",
					"file": true,
					"size": 15,
					"modificationTime": 1531498282315,
					"name": "log.log",
					"persission": "rw-r--r--",
					"accessTime": 1531498282247
				}, {
					"size": 42,
					"path": "/manuales",
					"modificationTime": 1531835155707,
					"name": "manuales",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 42,
					"file": false
				}, {
					"size": 2,
					"path": "/python",
					"modificationTime": 1531839385584,
					"name": "python",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 2,
					"file": false
				}, {
					"size": 5,
					"path": "/src",
					"modificationTime": 1531849326802,
					"name": "src",
					"replication": 0,
					"accessTime": 0,
					"mime": "inode/directory",
					"persission": "rwxr-xr-x",
					"elements": 5,
					"file": false
				}, {
					"size": 1212,
					"path": "/streaming.sh",
					"modificationTime": 1531363292061,
					"name": "streaming.sh",
					"replication": 3,
					"accessTime": 1531363291961,
					"mime": "application/x-sh",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"replication": 3,
					"path": "/ted.php",
					"file": true,
					"size": 31878,
					"modificationTime": 1531364239620,
					"name": "ted.php",
					"persission": "rw-r--r--",
					"accessTime": 1531364239568
				}, {
					"size": 23033908,
					"path": "/vlc-record-2017-12-28-21h22m49s-david@orchi ~_spark_spark-2.0.0-bin-hadoop2.7-.avi",
					"modificationTime": 1531707590686,
					"name": "vlc-record-2017-12-28-21h22m49s-david@orchi ~_spark_spark-2.0.0-bin-hadoop2.7-.avi",
					"replication": 3,
					"accessTime": 1531707584464,
					"mime": "video/x-msvideo",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1,
					"path": "/webapporchi",
					"modificationTime": 1531849728025,
					"name": "webapporchi",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 1,
					"file": false
				}, {
					"size": 5,
					"path": "/z",
					"modificationTime": 1531840647596,
					"name": "z",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 5,
					"file": false
				}],
				"size": 1874545160,
				"directoryCount": 1831,
				"fileCount": 9173,
				"time": 1677
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerInfo.java": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerInfo.java",
				"file": true,
				"data": {
					"size": 2429,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerInfo.java",
					"modificationTime": 1531708177349,
					"name": "XMPPServerInfo.java",
					"fileBase64Content": "LyoqDQogKiAkUkNTZmlsZSQNCiAqICRSZXZpc2lvbjogMTI4ICQNCiAqICREYXRlOiAyMDA0LTEwLTI1IDIwOjQyOjAwIC0wMzAwIChNb24sIDI1IE9jdCAyMDA0KSAkDQogKg0KICogQ29weXJpZ2h0IChDKSAyMDA0LTIwMDggSml2ZSBTb2Z0d2FyZS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4NCiAqDQogKiBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsNCiAqIHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aCB0aGUgTGljZW5zZS4NCiAqIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0aGUgTGljZW5zZSBhdA0KICoNCiAqICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjANCiAqDQogKiBVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlDQogKiBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLA0KICogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuDQogKiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kDQogKiBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4NCiAqLw0KDQpwYWNrYWdlIG9yZy5qaXZlc29mdHdhcmUub3BlbmZpcmU7DQoNCmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLnV0aWwuVmVyc2lvbjsNCg0KaW1wb3J0IGphdmEudXRpbC5Db2xsZWN0aW9uOw0KaW1wb3J0IGphdmEudXRpbC5EYXRlOw0KDQovKioNCiAqIEluZm9ybWF0aW9uICdzbmFwc2hvdCcgb2YgYSBzZXJ2ZXIncyBzdGF0ZS4gVXNlZnVsIGZvciBzdGF0aXN0aWNzDQogKiBnYXRoZXJpbmcgYW5kIGFkbWluaXN0cmF0aW9uIGRpc3BsYXkuDQogKg0KICogQGF1dGhvciBJYWluIFNoaWdlb2thDQogKi8NCnB1YmxpYyBpbnRlcmZhY2UgWE1QUFNlcnZlckluZm8gew0KDQogICAgLyoqDQogICAgICogT2J0YWluIHRoZSBzZXJ2ZXIncyB2ZXJzaW9uIGluZm9ybWF0aW9uLiBUeXBpY2FsbHkgdXNlZCBmb3IgaXE6dmVyc2lvbg0KICAgICAqIGFuZCBsb2dnaW5nIGluZm9ybWF0aW9uLg0KICAgICAqDQogICAgICogQHJldHVybiB0aGUgdmVyc2lvbiBvZiB0aGUgc2VydmVyLg0KICAgICAqLw0KICAgIFZlcnNpb24gZ2V0VmVyc2lvbigpOw0KDQogICAgLyoqDQogICAgICogT2J0YWluIHRoZSBob3N0IG5hbWUgKElQIGFkZHJlc3Mgb3IgaG9zdG5hbWUpIG9mIHRoaXMgc2VydmVyIG5vZGUuDQogICAgICoNCiAgICAgKiBAcmV0dXJuIHRoZSBzZXJ2ZXIncyBob3N0IG5hbWUgYXMgYW4gSVAgYWRkcmVzcyBvciBob3N0IG5hbWUuDQogICAgICovDQogICAgU3RyaW5nIGdldEhvc3RuYW1lKCk7DQoNCiAgICAvKioNCiAgICAgKiBPYnRhaW4gdGhlIHNlcnZlciBYTVBQIGRvbWFpbiBuYW1lLiBOb3RlIHRoYXQsIGlmIHVuY29uZmlndXJlZCwgdGhlDQogICAgICogcmV0dXJuZWQgdmFsdWUgd2lsbCBlcXVhbCB0aGUgaG9zdG5hbWUgb3IgSVAgYWRkcmVzcyBvZiB0aGUgc2VydmVyLg0KICAgICAqDQogICAgICogQHJldHVybiB0aGUgbmFtZSBvZiB0aGUgWE1QUCBkb21haW4gdGhhdCB0aGlzIHNlcnZlciBpcyBwYXJ0IG9mLg0KICAgICAqLw0KICAgIFN0cmluZyBnZXRYTVBQRG9tYWluKCk7DQoNCiAgICAvKioNCiAgICAgKiBTZXQgdGhlIHNlcnZlciBYTVBQIGRvbWFpbiBuYW1lLiBUaGUgc2VydmVyIG11c3QgYmUNCiAgICAgKiByZXN0YXJ0ZWQgZm9yIHRoaXMgY2hhbmdlIHRvIHRha2UgZWZmZWN0Lg0KICAgICAqDQogICAgICogQHBhcmFtIGRvbWFpbk5hbWUNCiAgICAgKiAgICAgICAgICAgICB0aGUgWE1QUCBkb21haW4gdGhhdCB0aGlzIHNlcnZlciBpcyBwYXJ0IG9mLg0KICAgICAqLw0KICAgIHZvaWQgc2V0WE1QUERvbWFpbihTdHJpbmcgZG9tYWluTmFtZSk7DQoNCiAgICAvKioNCiAgICAgKiBPYnRhaW4gdGhlIGRhdGUgd2hlbiB0aGUgc2VydmVyIHdhcyBsYXN0IHN0YXJ0ZWQuDQogICAgICoNCiAgICAgKiBAcmV0dXJuIHRoZSBkYXRlIHRoZSBzZXJ2ZXIgd2FzIHN0YXJ0ZWQgb3IgbnVsbCBpZiBzZXJ2ZXIgaGFzIG5vdCBiZWVuIHN0YXJ0ZWQuDQogICAgICovDQogICAgRGF0ZSBnZXRMYXN0U3RhcnRlZCgpOw0KDQogICAgLyoqDQogICAgICogT2J0YWluIHRoZSBzZXJ2ZXIgcG9ydHMgYWN0aXZlIG9uIHRoaXMgc2VydmVyLg0KICAgICAqDQogICAgICogQHJldHVybiBhbiBpdGVyYXRvciBvdmVyIHRoZSBzZXJ2ZXIgcG9ydHMgZm9yIHRoaXMgc2VydmVyLg0KICAgICAqLw0KICAgIENvbGxlY3Rpb248U2VydmVyUG9ydD4gZ2V0U2VydmVyUG9ydHMoKTsNCn0=",
					"accessTime": 1531708177324,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				},
				"time": 66
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement",
				"file": false,
				"data": [{
					"size": 9521,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java",
					"modificationTime": 1531708225867,
					"name": "StreamManager.java",
					"replication": 3,
					"accessTime": 1531708225820,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}],
				"size": 9521,
				"directoryCount": 1,
				"fileCount": 1,
				"time": 75
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire",
				"file": false,
				"data": [{
					"size": 7570,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/Channel.java",
					"modificationTime": 1531708174217,
					"name": "Channel.java",
					"replication": 3,
					"accessTime": 1531708174186,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1424,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/ChannelHandler.java",
					"modificationTime": 1531708174260,
					"name": "ChannelHandler.java",
					"replication": 3,
					"accessTime": 1531708174237,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1107,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/ChannelNotFoundException.java",
					"modificationTime": 1531708174305,
					"name": "ChannelNotFoundException.java",
					"replication": 3,
					"accessTime": 1531708174281,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 19698,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/Connection.java",
					"modificationTime": 1531708174349,
					"name": "Connection.java",
					"replication": 3,
					"accessTime": 1531708174325,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1217,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/ConnectionCloseListener.java",
					"modificationTime": 1531708174395,
					"name": "ConnectionCloseListener.java",
					"replication": 3,
					"accessTime": 1531708174370,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 8646,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/ConnectionManager.java",
					"modificationTime": 1531708174442,
					"name": "ConnectionManager.java",
					"replication": 3,
					"accessTime": 1531708174414,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 6269,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/FlashCrossDomainHandler.java",
					"modificationTime": 1531708174538,
					"name": "FlashCrossDomainHandler.java",
					"replication": 3,
					"accessTime": 1531708174475,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 2433,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/IQHandlerInfo.java",
					"modificationTime": 1531708174582,
					"name": "IQHandlerInfo.java",
					"replication": 3,
					"accessTime": 1531708174559,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 24961,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/IQRouter.java",
					"modificationTime": 1531708174684,
					"name": "IQRouter.java",
					"replication": 3,
					"accessTime": 1531708174603,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 5584,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/JMXManager.java",
					"modificationTime": 1531708174860,
					"name": "JMXManager.java",
					"replication": 3,
					"accessTime": 1531708174836,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 7798,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/LocalSessionManager.java",
					"modificationTime": 1531708174905,
					"name": "LocalSessionManager.java",
					"replication": 3,
					"accessTime": 1531708174880,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 13685,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/MessageRouter.java",
					"modificationTime": 1531708175104,
					"name": "MessageRouter.java",
					"replication": 3,
					"accessTime": 1531708175036,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 19839,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/MulticastRouter.java",
					"modificationTime": 1531708175570,
					"name": "MulticastRouter.java",
					"replication": 3,
					"accessTime": 1531708175125,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1571,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/OfflineMessage.java",
					"modificationTime": 1531708175737,
					"name": "OfflineMessage.java",
					"replication": 3,
					"accessTime": 1531708175590,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1530,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/OfflineMessageListener.java",
					"modificationTime": 1531708175780,
					"name": "OfflineMessageListener.java",
					"replication": 3,
					"accessTime": 1531708175757,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 21167,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/OfflineMessageStore.java",
					"modificationTime": 1531708175836,
					"name": "OfflineMessageStore.java",
					"replication": 3,
					"accessTime": 1531708175807,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 10899,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/OfflineMessageStrategy.java",
					"modificationTime": 1531708175903,
					"name": "OfflineMessageStrategy.java",
					"replication": 3,
					"accessTime": 1531708175857,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1593,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/PacketDeliverer.java",
					"modificationTime": 1531708175948,
					"name": "PacketDeliverer.java",
					"replication": 3,
					"accessTime": 1531708175923,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1149,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/PacketException.java",
					"modificationTime": 1531708175991,
					"name": "PacketException.java",
					"replication": 3,
					"accessTime": 1531708175968,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1661,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/PacketRouter.java",
					"modificationTime": 1531708176037,
					"name": "PacketRouter.java",
					"replication": 3,
					"accessTime": 1531708176012,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 6262,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/PresenceManager.java",
					"modificationTime": 1531708176080,
					"name": "PresenceManager.java",
					"replication": 3,
					"accessTime": 1531708176056,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 10242,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/PresenceRouter.java",
					"modificationTime": 1531708176137,
					"name": "PresenceRouter.java",
					"replication": 3,
					"accessTime": 1531708176107,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 9346,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/PrivateStorage.java",
					"modificationTime": 1531708176184,
					"name": "PrivateStorage.java",
					"replication": 3,
					"accessTime": 1531708176156,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1188,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/RemoteConnectionFailedException.java",
					"modificationTime": 1531708176238,
					"name": "RemoteConnectionFailedException.java",
					"replication": 3,
					"accessTime": 1531708176213,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1708,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/RemotePacketRouter.java",
					"modificationTime": 1531708176280,
					"name": "RemotePacketRouter.java",
					"replication": 3,
					"accessTime": 1531708176260,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1360,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/RoutableChannelHandler.java",
					"modificationTime": 1531708176326,
					"name": "RoutableChannelHandler.java",
					"replication": 3,
					"accessTime": 1531708176301,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 18779,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/RoutingTable.java",
					"modificationTime": 1531708176413,
					"name": "RoutingTable.java",
					"replication": 3,
					"accessTime": 1531708176345,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4199,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/ServerPort.java",
					"modificationTime": 1531708176591,
					"name": "ServerPort.java",
					"replication": 3,
					"accessTime": 1531708176567,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 72875,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/SessionManager.java",
					"modificationTime": 1531708176690,
					"name": "SessionManager.java",
					"replication": 3,
					"accessTime": 1531708176611,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1989,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/SessionNotFoundException.java",
					"modificationTime": 1531708176870,
					"name": "SessionNotFoundException.java",
					"replication": 3,
					"accessTime": 1531708176845,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 4343,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/SessionPacketRouter.java",
					"modificationTime": 1531708176914,
					"name": "SessionPacketRouter.java",
					"replication": 3,
					"accessTime": 1531708176889,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 14077,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/SessionResultFilter.java",
					"modificationTime": 1531708176959,
					"name": "SessionResultFilter.java",
					"replication": 3,
					"accessTime": 1531708176935,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1139,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/SharedGroupException.java",
					"modificationTime": 1531708177016,
					"name": "SharedGroupException.java",
					"replication": 3,
					"accessTime": 1531708176988,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1084,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/StreamID.java",
					"modificationTime": 1531708177070,
					"name": "StreamID.java",
					"replication": 3,
					"accessTime": 1531708177046,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1072,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/StreamIDFactory.java",
					"modificationTime": 1531708177125,
					"name": "StreamIDFactory.java",
					"replication": 3,
					"accessTime": 1531708177091,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1737,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPContextListener.java",
					"modificationTime": 1531708177171,
					"name": "XMPPContextListener.java",
					"replication": 3,
					"accessTime": 1531708177145,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 56613,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServer.java",
					"modificationTime": 1531708177283,
					"name": "XMPPServer.java",
					"replication": 3,
					"accessTime": 1531708177202,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 2429,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerInfo.java",
					"modificationTime": 1531708177349,
					"name": "XMPPServerInfo.java",
					"replication": 3,
					"accessTime": 1531708177324,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1495,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/XMPPServerListener.java",
					"modificationTime": 1531708177403,
					"name": "XMPPServerListener.java",
					"replication": 3,
					"accessTime": 1531708177380,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 3,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin",
					"modificationTime": 1531708177523,
					"name": "admin",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 3,
					"file": false
				}, {
					"size": 7,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/audit",
					"modificationTime": 1531708179075,
					"name": "audit",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 7,
					"file": false
				}, {
					"size": 19,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/auth",
					"modificationTime": 1531708181533,
					"name": "auth",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 19,
					"file": false
				}, {
					"size": 3,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/carbons",
					"modificationTime": 1531708181695,
					"name": "carbons",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 3,
					"file": false
				}, {
					"size": 5,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/cluster",
					"modificationTime": 1531708181972,
					"name": "cluster",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 5,
					"file": false
				}, {
					"size": 7,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/commands",
					"modificationTime": 1531708184857,
					"name": "commands",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 7,
					"file": false
				}, {
					"size": 8,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/component",
					"modificationTime": 1531708185956,
					"name": "component",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 8,
					"file": false
				}, {
					"size": 17,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/container",
					"modificationTime": 1531708186921,
					"name": "container",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 17,
					"file": false
				}, {
					"size": 8,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/crowd",
					"modificationTime": 1531708187346,
					"name": "crowd",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 8,
					"file": false
				}, {
					"size": 12,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/disco",
					"modificationTime": 1531708188496,
					"name": "disco",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 12,
					"file": false
				}, {
					"size": 3,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/entitycaps",
					"modificationTime": 1531708188699,
					"name": "entitycaps",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 3,
					"file": false
				}, {
					"size": 9,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/event",
					"modificationTime": 1531708189252,
					"name": "event",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 9,
					"file": false
				}, {
					"size": 8,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/filetransfer",
					"modificationTime": 1531708189680,
					"name": "filetransfer",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 8,
					"file": false
				}, {
					"size": 4,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/forms",
					"modificationTime": 1531708190094,
					"name": "forms",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 4,
					"file": false
				}, {
					"size": 2,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/forward",
					"modificationTime": 1531708190363,
					"name": "forward",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 2,
					"file": false
				}, {
					"size": 16,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/group",
					"modificationTime": 1531708191339,
					"name": "group",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 16,
					"file": false
				}, {
					"size": 22,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/handler",
					"modificationTime": 1531708193126,
					"name": "handler",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 22,
					"file": false
				}, {
					"size": 12,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/http",
					"modificationTime": 1531708194004,
					"name": "http",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 12,
					"file": false
				}, {
					"size": 5,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/interceptor",
					"modificationTime": 1531708194748,
					"name": "interceptor",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 5,
					"file": false
				}, {
					"size": 8,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/keystore",
					"modificationTime": 1531708195702,
					"name": "keystore",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 8,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/launcher",
					"modificationTime": 1531708196191,
					"name": "launcher",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 8,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/ldap",
					"modificationTime": 1531708197348,
					"name": "ldap",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 8,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/lockout",
					"modificationTime": 1531708197827,
					"name": "lockout",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 10,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/mediaproxy",
					"modificationTime": 1531708198613,
					"name": "mediaproxy",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 10,
					"file": false
				}, {
					"size": 22,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/muc",
					"modificationTime": 1531708204603,
					"name": "muc",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 22,
					"file": false
				}, {
					"size": 7,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/multiplex",
					"modificationTime": 1531708208174,
					"name": "multiplex",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 7,
					"file": false
				}, {
					"size": 33,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/net",
					"modificationTime": 1531708212194,
					"name": "net",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 33,
					"file": false
				}, {
					"size": 12,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/nio",
					"modificationTime": 1531708213181,
					"name": "nio",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 12,
					"file": false
				}, {
					"size": 5,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/pep",
					"modificationTime": 1531708213574,
					"name": "pep",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 5,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/privacy",
					"modificationTime": 1531708214058,
					"name": "privacy",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 16,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/pubsub",
					"modificationTime": 1531708217708,
					"name": "pubsub",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 16,
					"file": false
				}, {
					"size": 3,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/resultsetmanager",
					"modificationTime": 1531708217982,
					"name": "resultsetmanager",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 3,
					"file": false
				}, {
					"size": 8,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/roster",
					"modificationTime": 1531708218641,
					"name": "roster",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 8,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/sasl",
					"modificationTime": 1531708219133,
					"name": "sasl",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/security",
					"modificationTime": 1531708220083,
					"name": "security",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/server",
					"modificationTime": 1531708220882,
					"name": "server",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 18,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/session",
					"modificationTime": 1531708223289,
					"name": "session",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 18,
					"file": false
				}, {
					"size": 17,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/spi",
					"modificationTime": 1531708224921,
					"name": "spi",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 17,
					"file": false
				}, {
					"size": 2,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/starter",
					"modificationTime": 1531708225276,
					"name": "starter",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 2,
					"file": false
				}, {
					"size": 3,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/stats",
					"modificationTime": 1531708225710,
					"name": "stats",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 3,
					"file": false
				}, {
					"size": 1,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement",
					"modificationTime": 1531708225820,
					"name": "streammanagement",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 1,
					"file": false
				}, {
					"size": 1,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/transport",
					"modificationTime": 1531708225932,
					"name": "transport",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 1,
					"file": false
				}, {
					"size": 6,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/update",
					"modificationTime": 1531708226951,
					"name": "update",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 6,
					"file": false
				}, {
					"size": 16,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/user",
					"modificationTime": 1531708228434,
					"name": "user",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 16,
					"file": false
				}, {
					"size": 5,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/vcard",
					"modificationTime": 1531708228848,
					"name": "vcard",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 5,
					"file": false
				}, {
					"size": 1,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/webdav",
					"modificationTime": 1531708228950,
					"name": "webdav",
					"replication": 0,
					"accessTime": 0,
					"persission": "rwxr-xr-x",
					"elements": 1,
					"file": false
				}],
				"size": 4831424,
				"directoryCount": 60,
				"fileCount": 549,
				"time": 340
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin",
				"file": false,
				"data": [{
					"size": 10698,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/AdminManager.java",
					"modificationTime": 1531708177458,
					"name": "AdminManager.java",
					"replication": 3,
					"accessTime": 1531708177435,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 1591,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/AdminProvider.java",
					"modificationTime": 1531708177503,
					"name": "AdminProvider.java",
					"replication": 3,
					"accessTime": 1531708177479,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}, {
					"size": 7463,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java",
					"modificationTime": 1531708177949,
					"name": "DefaultAdminProvider.java",
					"replication": 3,
					"accessTime": 1531708177523,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				}],
				"size": 19752,
				"directoryCount": 1,
				"fileCount": 3,
				"time": 44
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java",
				"file": true,
				"data": {
					"size": 9521,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java",
					"modificationTime": 1531708225867,
					"name": "StreamManager.java",
					"fileBase64Content": "cGFja2FnZSBvcmcuaml2ZXNvZnR3YXJlLm9wZW5maXJlLnN0cmVhbW1hbmFnZW1lbnQ7CgppbXBvcnQgamF2YS5tYXRoLkJpZ0ludGVnZXI7CmltcG9ydCBqYXZhLm5ldC5Vbmtub3duSG9zdEV4Y2VwdGlvbjsKaW1wb3J0IGphdmEudXRpbC4qOwoKaW1wb3J0IG9yZy5kb200ai5FbGVtZW50OwppbXBvcnQgb3JnLmppdmVzb2Z0d2FyZS5vcGVuZmlyZS5Db25uZWN0aW9uOwppbXBvcnQgb3JnLmppdmVzb2Z0d2FyZS5vcGVuZmlyZS5QYWNrZXRSb3V0ZXI7CmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLnV0aWwuSml2ZUdsb2JhbHM7CmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLnV0aWwuWE1QUERhdGVUaW1lRm9ybWF0OwppbXBvcnQgb3JnLnNsZjRqLkxvZ2dlcjsKaW1wb3J0IG9yZy5zbGY0ai5Mb2dnZXJGYWN0b3J5OwppbXBvcnQgb3JnLnhtcHAucGFja2V0LkpJRDsKaW1wb3J0IG9yZy54bXBwLnBhY2tldC5NZXNzYWdlOwppbXBvcnQgb3JnLnhtcHAucGFja2V0LlBhY2tldDsKaW1wb3J0IG9yZy54bXBwLnBhY2tldC5QYWNrZXRFcnJvcjsKCi8qKgogKiBYRVAtMDE5OCBTdHJlYW0gTWFuYWdlci4KICogSGFuZGxlcyBjbGllbnQvc2VydmVyIG1lc3NhZ2VzIGFja25vd2xlZGdlbWVudC4KICoKICogQGF1dGhvciBqb25ueWhlYXZleQogKi8KcHVibGljIGNsYXNzIFN0cmVhbU1hbmFnZXIgewoKCXByaXZhdGUgZmluYWwgTG9nZ2VyIExvZzsKICAgIHB1YmxpYyBzdGF0aWMgY2xhc3MgVW5hY2tlZFBhY2tldCB7CgkJcHVibGljIGZpbmFsIGxvbmcgeDsKICAgICAgICBwdWJsaWMgZmluYWwgRGF0ZSB0aW1lc3RhbXAgPSBuZXcgRGF0ZSgpOwogICAgICAgIHB1YmxpYyBmaW5hbCBQYWNrZXQgcGFja2V0OwogICAgICAgIAogICAgICAgIHB1YmxpYyBVbmFja2VkUGFja2V0KGxvbmcgeCwgUGFja2V0IHApIHsKCQkJdGhpcy54ID0geDsKICAgICAgICAgICAgcGFja2V0ID0gcDsKICAgICAgICB9CiAgICB9CiAgICAKICAgIHB1YmxpYyBzdGF0aWMgZmluYWwgU3RyaW5nIFNNX0FDVElWRSA9ICJzdHJlYW0ubWFuYWdlbWVudC5hY3RpdmUiOwoKICAgIC8qKgogICAgICogU3RhbnphIG5hbWVzcGFjZXMKICAgICAqLwogICAgcHVibGljIHN0YXRpYyBmaW5hbCBTdHJpbmcgTkFNRVNQQUNFX1YyID0gInVybjp4bXBwOnNtOjIiOwogICAgcHVibGljIHN0YXRpYyBmaW5hbCBTdHJpbmcgTkFNRVNQQUNFX1YzID0gInVybjp4bXBwOnNtOjMiOwoKCS8qKgoJICogQ29ubmVjdGlvbiAoc3RyZWFtKSB0byBjbGllbnQgZm9yIHRoZSBzZXNzaW9uIHRoZSBtYW5hZ2VyIGJlbG9uZ3MgdG8KCSAqLwoJcHJpdmF0ZSBmaW5hbCBDb25uZWN0aW9uIGNvbm5lY3Rpb247CgoJLyoqCiAgICAgKiBOYW1lc3BhY2UgdG8gYmUgdXNlZCBpbiBzdGFuemFzIHNlbnQgdG8gY2xpZW50IChkZXBlbmRpbmcgb24gWEVQLTAxOTggdmVyc2lvbiB1c2VkIGJ5IGNsaWVudCkKICAgICAqLwogICAgcHJpdmF0ZSBTdHJpbmcgbmFtZXNwYWNlOwoKICAgIC8qKgogICAgICogQ291bnQgb2YgaG93IG1hbnkgc3Rhbnphcy9wYWNrZXRzCiAgICAgKiBzZW50IGZyb20gdGhlIGNsaWVudCB0aGF0IHRoZSBzZXJ2ZXIgaGFzIHByb2Nlc3NlZAogICAgICovCiAgICBwcml2YXRlIGxvbmcgc2VydmVyUHJvY2Vzc2VkU3RhbnphcyA9IDA7CgogICAgLyoqCiAJICogQ291bnQgb2YgaG93IG1hbnkgc3Rhbnphcy9wYWNrZXRzCiAgICAgKiBzZW50IGZyb20gdGhlIHNlcnZlciB0aGF0IHRoZSBjbGllbnQgaGFzIHByb2Nlc3NlZAogICAgICovCiAgICBwcml2YXRlIGxvbmcgY2xpZW50UHJvY2Vzc2VkU3RhbnphcyA9IDA7CgogICAgc3RhdGljIHByaXZhdGUgbG9uZyBtYXNrID0gbmV3IEJpZ0ludGVnZXIoIjIiKS5wb3coMzIpLmxvbmdWYWx1ZSgpIC0gMTsgLy8gVGhpcyBpcyB1c2VkIHRvIGVtdWxhdGUgcm9sbG92ZXIuCgogICAgLyoqCiAgICAgKiBDb2xsZWN0aW9uIG9mIHN0YW56YXMvcGFja2V0cyBzZW50IHRvIGNsaWVudCB0aGF0IGhhdmVuJ3QgYmVlbiBhY2tub3dsZWRnZWQuCiAgICAgKi8KICAgIHByaXZhdGUgRGVxdWU8VW5hY2tlZFBhY2tldD4gdW5hY2tub3dsZWRnZWRTZXJ2ZXJTdGFuemFzID0gbmV3IExpbmtlZExpc3Q8PigpOwoKICAgIHB1YmxpYyBTdHJlYW1NYW5hZ2VyKENvbm5lY3Rpb24gY29ubmVjdGlvbikgewoJCVN0cmluZyBhZGRyZXNzOwoJCXRyeSB7CgkJCWFkZHJlc3MgPSBjb25uZWN0aW9uLmdldEhvc3RBZGRyZXNzKCk7CgkJfQoJCWNhdGNoICggVW5rbm93bkhvc3RFeGNlcHRpb24gZSApCgkJewoJCQlhZGRyZXNzID0gbnVsbDsKCQl9CgoJCXRoaXMuTG9nID0gTG9nZ2VyRmFjdG9yeS5nZXRMb2dnZXIoU3RyZWFtTWFuYWdlci5jbGFzcyArICJbIisgKGFkZHJlc3MgPT0gbnVsbCA/ICIodW5rbm93biBhZGRyZXNzKSIgOiBhZGRyZXNzKSArIl0iICk7CiAgICAJdGhpcy5jb25uZWN0aW9uID0gY29ubmVjdGlvbjsKICAgIH0KCgkvKioKCSAqIFByb2Nlc3NlcyBhIHN0cmVhbSBtYW5hZ2VtZW50IGVsZW1lbnQuCgkgKgoJICogQHBhcmFtIGVsZW1lbnQgVGhlIHN0cmVhbSBtYW5hZ2VtZW50IGVsZW1lbnQgdG8gYmUgcHJvY2Vzc2VkLgoJICogQHBhcmFtIG9uQmVoYWxmT2YgVGhlIChmdWxsKSBKSUQgb2YgdGhlIGVudGl0eSBmb3Igd2hpY2ggdGhlIGVsZW1lbnQgaXMgcHJvY2Vzc2VkLgoJICovCglwdWJsaWMgdm9pZCBwcm9jZXNzKCBFbGVtZW50IGVsZW1lbnQsIEpJRCBvbkJlaGFsZk9mICkKCXsKCQlzd2l0Y2goZWxlbWVudC5nZXROYW1lKCkpIHsKCQkJY2FzZSAiZW5hYmxlIjoKCQkJCWVuYWJsZSggb25CZWhhbGZPZiwgZWxlbWVudC5nZXROYW1lc3BhY2UoKS5nZXRTdHJpbmdWYWx1ZSgpICk7CgkJCQlicmVhazsKCQkJY2FzZSAiciI6CgkJCQlzZW5kU2VydmVyQWNrbm93bGVkZ2VtZW50KCk7CgkJCQlicmVhazsKCQkJY2FzZSAiYSI6CgkJCQlwcm9jZXNzQ2xpZW50QWNrbm93bGVkZ2VtZW50KCBlbGVtZW50KTsKCQkJCWJyZWFrOwoJCQlkZWZhdWx0OgoJCQkJc2VuZFVuZXhwZWN0ZWRFcnJvcigpOwoJCX0KCX0KCgkvKioKCSAqIEF0dGVtcHRzIHRvIGVuYWJsZSBTdHJlYW0gTWFuYWdlbWVudCBmb3IgdGhlIGVudGl0eSBpZGVudGlmaWVkIGJ5IHRoZSBwcm92aWRlZCBKSUQuCgkgKgoJICogQHBhcmFtIG9uQmVoYWxmT2YgVGhlIGFkZHJlc3Mgb2YgdGhlIGVudGl0eSBmb3Igd2hpY2ggU00gaXMgdG8gYmUgZW5hYmxlZC4KCSAqIEBwYXJhbSBuYW1lc3BhY2UgVGhlIG5hbWVzcGFjZSB0aGF0IGRlZmluZXMgd2hhdCB2ZXJzaW9uIG9mIFNNIGlzIHRvIGJlIGVuYWJsZWQuCgkgKi8KCXByaXZhdGUgdm9pZCBlbmFibGUoIEpJRCBvbkJlaGFsZk9mLCBTdHJpbmcgbmFtZXNwYWNlICkKCXsKCQkvLyBFbnN1cmUgdGhhdCByZXNvdXJjZSBiaW5kaW5nIGhhcyBvY2N1cnJlZC4KCQlpZiggb25CZWhhbGZPZi5nZXRSZXNvdXJjZSgpID09IG51bGwgKSB7CgkJCXNlbmRVbmV4cGVjdGVkRXJyb3IoKTsKCQkJcmV0dXJuOwoJCX0KCgkJc3luY2hyb25pemVkICggdGhpcyApCgkJewoJCQkvLyBEbyBub3RoaW5nIGlmIGFscmVhZHkgZW5hYmxlZAoJCQlpZiAoIGlzRW5hYmxlZCgpICkKCQkJewoJCQkJcmV0dXJuOwoJCQl9CgoJCQl0aGlzLm5hbWVzcGFjZSA9IG5hbWVzcGFjZTsKCQl9CgoJCS8vIFNlbmQgY29uZmlybWF0aW9uIHRvIHRoZSByZXF1ZXN0ZWUuCgkJY29ubmVjdGlvbi5kZWxpdmVyUmF3VGV4dCggU3RyaW5nLmZvcm1hdCggIjxlbmFibGVkIHhtbG5zPSclcycvPiIsIG5hbWVzcGFjZSApICk7Cgl9CgoJLyoqCiAgICAgKiBTZW5kcyBYRVAtMDE5OCBhY2tub3dsZWRnZW1lbnQgJmx0O2EgLyZndDsgdG8gY2xpZW50IGZyb20gc2VydmVyCiAgICAgKi8KCXB1YmxpYyB2b2lkIHNlbmRTZXJ2ZXJBY2tub3dsZWRnZW1lbnQoKSB7CgkJaWYoaXNFbmFibGVkKCkpIHsKCQkJU3RyaW5nIGFjayA9IFN0cmluZy5mb3JtYXQoIjxhIHhtbG5zPSclcycgaD0nJXMnIC8+IiwgbmFtZXNwYWNlLCBzZXJ2ZXJQcm9jZXNzZWRTdGFuemFzICYgbWFzayk7CgkJCWNvbm5lY3Rpb24uZGVsaXZlclJhd1RleHQoIGFjayApOwoJCX0KCX0KCgkvKioKCSAqIFNlbmRzIFhFUC0wMTk4IHJlcXVlc3QgPHIgLz4gdG8gY2xpZW50IGZyb20gc2VydmVyCgkgKi8KCXByaXZhdGUgdm9pZCBzZW5kU2VydmVyUmVxdWVzdCgpIHsKCQlpZihpc0VuYWJsZWQoKSkgewoJCQlTdHJpbmcgcmVxdWVzdCA9IFN0cmluZy5mb3JtYXQoIjxyIHhtbG5zPSclcycgLz4iLCBuYW1lc3BhY2UpOwoJCQljb25uZWN0aW9uLmRlbGl2ZXJSYXdUZXh0KCByZXF1ZXN0ICk7CgkJfQoJfQoKCS8qKgoJICogU2VuZCBhbiBlcnJvciBpZiBhIFhFUC0wMTk4IHN0YW56YSBpcyByZWNlaXZlZCBhdCBhbiB1bmV4cGVjdGVkIHRpbWUuCgkgKiBlLmcuIGJlZm9yZSByZXNvdXJjZS1iaW5kaW5nIGhhcyBjb21wbGV0ZWQuCgkgKi8KCXByaXZhdGUgdm9pZCBzZW5kVW5leHBlY3RlZEVycm9yKCkgewoJCWNvbm5lY3Rpb24uZGVsaXZlclJhd1RleHQoCgkJCQlTdHJpbmcuZm9ybWF0KCAiPGZhaWxlZCB4bWxucz0nJXMnPiIsIG5hbWVzcGFjZSApCgkJCQkJCSsgbmV3IFBhY2tldEVycm9yKCBQYWNrZXRFcnJvci5Db25kaXRpb24udW5leHBlY3RlZF9yZXF1ZXN0ICkudG9YTUwoKQoJCQkJCQkrICI8L2ZhaWxlZD4iCgkJKTsKCX0KCgkvKioKCSAqIFJlY2VpdmUgYW5kIHByb2Nlc3MgYWNrbm93bGVkZ2VtZW50IHBhY2tldCBmcm9tIGNsaWVudAoJICogQHBhcmFtIGFjayBYRVAtMDE5OCBhY2tub3dsZWRnZW1lbnQgPGEgLz4gc3RhbnphIHRvIHByb2Nlc3MKCSAqLwoJcHJpdmF0ZSB2b2lkIHByb2Nlc3NDbGllbnRBY2tub3dsZWRnZW1lbnQoRWxlbWVudCBhY2spIHsKCQlpZihpc0VuYWJsZWQoKSkgewoJCQlpZiAoYWNrLmF0dHJpYnV0ZSgiaCIpICE9IG51bGwpIHsKCQkJCWZpbmFsIGxvbmcgaCA9IExvbmcudmFsdWVPZihhY2suYXR0cmlidXRlVmFsdWUoImgiKSk7CgoJCQkJTG9nLmRlYnVnKCAiUmVjZWl2ZWQgYWNrbm93bGVkZ2VtZW50IGZyb20gY2xpZW50OiBoPXt9IiwgaCApOwoJCQkJc3luY2hyb25pemVkICh0aGlzKSB7CgoJCQkJCWlmICggIXVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5pc0VtcHR5KCkgJiYgaCA+IHVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5nZXRMYXN0KCkueCApIHsKCQkJCQkJTG9nLndhcm4oICJDbGllbnQgYWNrbm93bGVkZ2VzIHN0YW56YXMgdGhhdCB3ZSBkaWRuJ3Qgc2VudCEgQ2xpZW50IEFjayBoOiB7fSwgb3VyIGxhc3Qgc3RhbnphOiB7fSIsIGgsIHVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5nZXRMYXN0KCkueCApOwoJCQkJCX0KCgkJCQkJY2xpZW50UHJvY2Vzc2VkU3RhbnphcyA9IGg7CgoJCQkJCS8vIFJlbW92ZSBzdGFuemFzIGZyb20gdGVtcG9yYXJ5IHN0b3JhZ2UgYXMgbm93IGFja25vd2xlZGdlZAoJCQkJCUxvZy50cmFjZSggIkJlZm9yZSBwcm9jZXNzaW5nIGNsaWVudCBBY2sgKGg9e30pOiB7fSB1bmFja25vd2xlZGdlZCBzdGFuemFzLiIsIGgsIHVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5zaXplKCkgKTsKCgkJCQkJLy8gUG9wIGFsbCBhY2tub3dsZWRnZWQgc3Rhbnphcy4KCQkJCQl3aGlsZSggIXVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5pc0VtcHR5KCkgJiYgdW5hY2tub3dsZWRnZWRTZXJ2ZXJTdGFuemFzLmdldEZpcnN0KCkueCA8PSBoICkKCQkJCQl7CgkJCQkJCXVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5yZW1vdmVGaXJzdCgpOwoJCQkJCX0KCgkJCQkJLy8gRW5zdXJlIHRoYXQgdW5hY2tub3dsZWRnZWQgc3RhbnphcyBhcmUgcHVyZ2VkIGFmdGVyIHRoZSBjbGllbnQgcm9sbGVkIG92ZXIgJ2gnIHdoaWNoIG9jY3VycyBhdCBoPSAoMl4zMiktMQoJCQkJCWZpbmFsIGludCBtYXhVbmFja2VkID0gZ2V0TWF4aW11bVVuYWNrbm93bGVkZ2VkU3RhbnphcygpOwoJCQkJCWZpbmFsIGJvb2xlYW4gY2xpZW50SGFkUm9sbE92ZXIgPSBoIDwgbWF4VW5hY2tlZCAmJiAhdW5hY2tub3dsZWRnZWRTZXJ2ZXJTdGFuemFzLmlzRW1wdHkoKSAmJiB1bmFja25vd2xlZGdlZFNlcnZlclN0YW56YXMuZ2V0TGFzdCgpLnggPiBtYXNrIC0gbWF4VW5hY2tlZDsKCQkJCQlpZiAoIGNsaWVudEhhZFJvbGxPdmVyICkKCQkJCQl7CgkJCQkJCUxvZy5pbmZvKCAiQ2xpZW50IHJvbGxlZCBvdmVyICdoJy4gUHVyZ2luZyBoaWdoLW51bWJlcmVkIHVuYWNrbm93bGVkZ2VkIHN0YW56YXMuIiApOwoJCQkJCQl3aGlsZSAoICF1bmFja25vd2xlZGdlZFNlcnZlclN0YW56YXMuaXNFbXB0eSgpICYmIHVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5nZXRMYXN0KCkueCA+IG1hc2sgLSBtYXhVbmFja2VkKQoJCQkJCQl7CgkJCQkJCQl1bmFja25vd2xlZGdlZFNlcnZlclN0YW56YXMucmVtb3ZlTGFzdCgpOwoJCQkJCQl9CgkJCQkJfQoKCQkJCQlMb2cudHJhY2UoICJBZnRlciBwcm9jZXNzaW5nIGNsaWVudCBBY2sgKGg9e30pOiB7fSB1bmFja25vd2xlZGdlZCBzdGFuemFzLiIsIGgsIHVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5zaXplKCkpOwoJCQkJfQoJCQl9CgkJfQoJfQoKCS8qKgoJICogUmVnaXN0ZXJzIHRoYXQgT3BlbmZpcmUgc2VuZHMgYSBzdGFuemEgdG8gdGhlIGNsaWVudCAod2hpY2ggaXMgZXhwZWN0ZWQgdG8gYmUgYWNrbm93bGVkZ2VkIGxhdGVyKS4KCSAqIEBwYXJhbSBwYWNrZXQgVGhlIHN0YW56YSB0aGF0IGlzIHNlbnQuCgkgKi8KCXB1YmxpYyB2b2lkIHNlbnRTdGFuemEoUGFja2V0IHBhY2tldCkgewoKCQlpZihpc0VuYWJsZWQoKSkgewoJCQlmaW5hbCBsb25nIHJlcXVlc3RGcmVxdWVuY3kgPSBKaXZlR2xvYmFscy5nZXRMb25nUHJvcGVydHkoICJzdHJlYW0ubWFuYWdlbWVudC5yZXF1ZXN0RnJlcXVlbmN5IiwgNSApOwoJCQlmaW5hbCBpbnQgc2l6ZTsKCgkJCXN5bmNocm9uaXplZCAodGhpcykKCQkJewoJCQkJLy8gVGhlIG5leHQgSUQgaXMgb25lIGhpZ2hlciB0aGFuIHRoZSBsYXN0IHN0YW56YSB0aGF0IHdhcyBzZW50ICh3aGljaCBtaWdodCBiZSB1bmFja25vd2xlZGdlZCEpCgkJCQlmaW5hbCBsb25nIHggPSAxICsgKCB1bmFja25vd2xlZGdlZFNlcnZlclN0YW56YXMuaXNFbXB0eSgpID8gY2xpZW50UHJvY2Vzc2VkU3RhbnphcyA6IHVuYWNrbm93bGVkZ2VkU2VydmVyU3Rhbnphcy5nZXRMYXN0KCkueCApOwoJCQkJdW5hY2tub3dsZWRnZWRTZXJ2ZXJTdGFuemFzLmFkZExhc3QoIG5ldyBTdHJlYW1NYW5hZ2VyLlVuYWNrZWRQYWNrZXQoIHgsIHBhY2tldC5jcmVhdGVDb3B5KCkgKSApOwoKCQkJCXNpemUgPSB1bmFja25vd2xlZGdlZFNlcnZlclN0YW56YXMuc2l6ZSgpOwoKCQkJCUxvZy50cmFjZSggIkFkZGVkIHN0YW56YSBvZiB0eXBlICd7fScgdG8gY29sbGVjdGlvbiBvZiB1bmFja25vd2xlZGdlZCBzdGFuemFzICh4PXt9KS4gQ29sbGVjdGlvbiBzaXplIGlzIG5vdyB7fS4iLCBwYWNrZXQuZ2V0RWxlbWVudCgpLmdldE5hbWUoKSwgeCwgc2l6ZSApOwoKCQkJCS8vIFByZXZlbnQga2VlcGluZyB0byBtYW55IHN0YW56YXMgaW4gbWVtb3J5LgoJCQkJaWYgKCBzaXplID4gZ2V0TWF4aW11bVVuYWNrbm93bGVkZ2VkU3RhbnphcygpICkKCQkJCXsKCQkJCQlMb2cud2FybiggIlRvIG1hbnkgc3RhbnphcyBnbyB1bmFja25vd2xlZGdlZCBmb3IgdGhpcyBjb25uZWN0aW9uLiBDbGVhcmluZyBxdWV1ZSBhbmQgZGlzYWJsaW5nIGZ1bmN0aW9uYWxpdHkuIiApOwoJCQkJCW5hbWVzcGFjZSA9IG51bGw7CgkJCQkJdW5hY2tub3dsZWRnZWRTZXJ2ZXJTdGFuemFzLmNsZWFyKCk7CgkJCQkJcmV0dXJuOwoJCQkJfQoJCQl9CgoJCQkvLyBXaGVuIHdlIGhhdmUgYSBzaXphYmxlIGFtb3VudCBvZiB1bmFja25vd2xlZGdlZCBzdGFuemFzLCByZXF1ZXN0IGFja25vd2xlZGdlbWVudC4KCQkJaWYgKCBzaXplICUgcmVxdWVzdEZyZXF1ZW5jeSA9PSAwICkgewoJCQkJTG9nLmRlYnVnKCAiUmVxdWVzdGluZyBhY2tub3dsZWRnZW1lbnQgZnJvbSBwZWVyLCBhcyB3ZSBoYXZlIHt9IG9yIG1vcmUgdW5hY2tub3dsZWRnZWQgc3Rhbnphcy4iLCByZXF1ZXN0RnJlcXVlbmN5ICk7CgkJCQlzZW5kU2VydmVyUmVxdWVzdCgpOwoJCQl9CgkJfQoKCX0KCglwdWJsaWMgdm9pZCBvbkNsb3NlKFBhY2tldFJvdXRlciByb3V0ZXIsIEpJRCBzZXJ2ZXJBZGRyZXNzKSB7CgkJLy8gUmUtZGVsaXZlciB1bmFja25vd2xlZGdlZCBzdGFuemFzIGZyb20gYnJva2VuIHN0cmVhbSAoWEVQLTAxOTgpCgkJc3luY2hyb25pemVkICh0aGlzKSB7CgkJCWlmKGlzRW5hYmxlZCgpKSB7CgkJCQluYW1lc3BhY2UgPSBudWxsOyAvLyBkaXNhYmxlIHN0cmVhbSBtYW5hZ2VtZW50LgoJCQkJZm9yIChTdHJlYW1NYW5hZ2VyLlVuYWNrZWRQYWNrZXQgdW5hY2tlZCA6IHVuYWNrbm93bGVkZ2VkU2VydmVyU3RhbnphcykgewoJCQkJCWlmICh1bmFja2VkLnBhY2tldCBpbnN0YW5jZW9mIE1lc3NhZ2UpIHsKCQkJCQkJTWVzc2FnZSBtID0gKE1lc3NhZ2UpIHVuYWNrZWQucGFja2V0OwoJCQkJCQlpZiAobS5nZXRFeHRlbnNpb24oImRlbGF5IiwgInVybjp4bXBwOmRlbGF5IikgPT0gbnVsbCkgewoJCQkJCQkJRWxlbWVudCBkZWxheUluZm9ybWF0aW9uID0gbS5hZGRDaGlsZEVsZW1lbnQoImRlbGF5IiwgInVybjp4bXBwOmRlbGF5Iik7CgkJCQkJCQlkZWxheUluZm9ybWF0aW9uLmFkZEF0dHJpYnV0ZSgic3RhbXAiLCBYTVBQRGF0ZVRpbWVGb3JtYXQuZm9ybWF0KHVuYWNrZWQudGltZXN0YW1wKSk7CgkJCQkJCQlkZWxheUluZm9ybWF0aW9uLmFkZEF0dHJpYnV0ZSgiZnJvbSIsIHNlcnZlckFkZHJlc3MudG9CYXJlSklEKCkpOwoJCQkJCQl9CgkJCQkJCXJvdXRlci5yb3V0ZSh1bmFja2VkLnBhY2tldCk7CgkJCQkJfQoJCQkJfQoJCQl9CgkJfQoKCX0KCgkvKioKCSAqIERldGVybWluZXMgd2hldGhlciBTdHJlYW0gTWFuYWdlbWVudCBlbmFibGVkIGZvciBzZXNzaW9uIHRoaXMKCSAqIG1hbmFnZXIgYmVsb25ncyB0by4KCSAqIEByZXR1cm4gdHJ1ZSB3aGVuIHN0cmVhbSBtYW5hZ2VtZW50IGlzIGVuYWJsZWQsIG90aGVyd2lzZSBmYWxzZS4KCSAqLwoJcHVibGljIGJvb2xlYW4gaXNFbmFibGVkKCkgewoJCXJldHVybiBuYW1lc3BhY2UgIT0gbnVsbDsKCX0KCgkvKioKCSAqIEluY3JlbWVudHMgdGhlIGNvdW50IG9mIHN0YW56YXMgcHJvY2Vzc2VkIGJ5IHRoZSBzZXJ2ZXIgc2luY2UKCSAqIFN0cmVhbSBNYW5hZ2VtZW50IHdhcyBlbmFibGVkLgoJICovCglwdWJsaWMgdm9pZCBpbmNyZW1lbnRTZXJ2ZXJQcm9jZXNzZWRTdGFuemFzKCkgewoJCWlmKGlzRW5hYmxlZCgpKSB7CgkJCXRoaXMuc2VydmVyUHJvY2Vzc2VkU3RhbnphcysrOwoJCX0KCX0KCgkvKioKCSAqIFRoZSBtYXhpbXVtIGFtb3VudCBvZiBzdGFuemFzIHdlIGtlZXAsIHdhaXRpbmcgZm9yIGFjay4KCSAqIEByZXR1cm4gVGhlIG1heGltdW0gbnVtYmVyIG9mIHN0YW56YXMuCgkgKi8KCXByaXZhdGUgaW50IGdldE1heGltdW1VbmFja25vd2xlZGdlZFN0YW56YXMoKQoJewoJCXJldHVybiBKaXZlR2xvYmFscy5nZXRJbnRQcm9wZXJ0eSggInN0cmVhbS5tYW5hZ2VtZW50Lm1heC11bmFja2VkIiwgMTAwMDAgKTsKCX0KfQo=",
					"accessTime": 1531708225820,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				},
				"time": 110
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java": {
				"status": "ok",
				"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java",
				"file": true,
				"data": {
					"size": 7463,
					"path": "/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java",
					"modificationTime": 1531708177949,
					"name": "DefaultAdminProvider.java",
					"fileBase64Content": "LyoqCiAqICRSZXZpc2lvbiQKICogJERhdGUkCiAqCiAqIENvcHlyaWdodCAoQykgMjAwNS0yMDA4IEppdmUgU29mdHdhcmUuIEFsbCByaWdodHMgcmVzZXJ2ZWQuCiAqCiAqIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGljZW5zZSIpOwogKiB5b3UgbWF5IG5vdCB1c2UgdGhpcyBmaWxlIGV4Y2VwdCBpbiBjb21wbGlhbmNlIHdpdGggdGhlIExpY2Vuc2UuCiAqIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0aGUgTGljZW5zZSBhdAogKgogKiAgICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCiAqCiAqIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4gd3JpdGluZywgc29mdHdhcmUKICogZGlzdHJpYnV0ZWQgdW5kZXIgdGhlIExpY2Vuc2UgaXMgZGlzdHJpYnV0ZWQgb24gYW4gIkFTIElTIiBCQVNJUywKICogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiAqIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJtaXNzaW9ucyBhbmQKICogbGltaXRhdGlvbnMgdW5kZXIgdGhlIExpY2Vuc2UuCiAqLwpwYWNrYWdlIG9yZy5qaXZlc29mdHdhcmUub3BlbmZpcmUuYWRtaW47CgppbXBvcnQgamF2YS51dGlsLkFycmF5TGlzdDsKaW1wb3J0IGphdmEudXRpbC5Db2xsZWN0aW9uOwppbXBvcnQgamF2YS51dGlsLkxpc3Q7CmltcG9ydCBqYXZhLnV0aWwuTWFwOwppbXBvcnQgamF2YS51dGlsLlN0cmluZ1Rva2VuaXplcjsKCmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLm9wZW5maXJlLlhNUFBTZXJ2ZXI7CmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLnV0aWwuSml2ZUdsb2JhbHM7CmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLnV0aWwuUHJvcGVydHlFdmVudERpc3BhdGNoZXI7CmltcG9ydCBvcmcuaml2ZXNvZnR3YXJlLnV0aWwuUHJvcGVydHlFdmVudExpc3RlbmVyOwppbXBvcnQgb3JnLmppdmVzb2Z0d2FyZS51dGlsLlN0cmluZ1V0aWxzOwppbXBvcnQgb3JnLnNsZjRqLkxvZ2dlcjsKaW1wb3J0IG9yZy5zbGY0ai5Mb2dnZXJGYWN0b3J5OwppbXBvcnQgb3JnLnhtcHAucGFja2V0LkpJRDsKCi8qKgogKiBIYW5kbGVzIGRlZmF1bHQgbWFuYWdlbWVudCBvZiBhZG1pbiB1c2Vycywgd2hpY2ggc3RvcmVzIHRoZSBsaXN0IGlmIGFjY291bnRzIGFzIGEgc3lzdGVtIHByb3BlcnR5LgogKgogKiBAYXV0aG9yIERhbmllbCBIZW5uaW5nZXIKICovCnB1YmxpYyBjbGFzcyBEZWZhdWx0QWRtaW5Qcm92aWRlciBpbXBsZW1lbnRzIEFkbWluUHJvdmlkZXIgewoKCXByaXZhdGUgc3RhdGljIGZpbmFsIExvZ2dlciBMb2cgPSBMb2dnZXJGYWN0b3J5LmdldExvZ2dlcihEZWZhdWx0QWRtaW5Qcm92aWRlci5jbGFzcyk7CgogICAgLyoqCiAgICAgKiBDb25zdHJ1Y3RzIGEgbmV3IERlZmF1bHRBZG1pblByb3ZpZGVyCiAgICAgKi8KICAgIHB1YmxpYyBEZWZhdWx0QWRtaW5Qcm92aWRlcigpIHsKCiAgICAgICAgLy8gQ29udmVydCBvbGQgb3BlbmZpcmUueG1sIHN0eWxlIHRvIG5ldyBwcm92aWRlciBzdHlsZSwgaWYgbmVjZXNzYXJ5LgogICAgICAgIExvZy5kZWJ1ZygiRGVmYXVsdEFkbWluUHJvdmlkZXI6IENvbnZlcnQgWE1MIHRvIHByb3ZpZGVyLiIpOwogICAgICAgIGNvbnZlcnRYTUxUb1Byb3ZpZGVyKCk7CgogICAgICAgIC8vIERldGVjdCB3aGVuIHRoZSBsaXN0IG9mIGFkbWluIHVzZXJzIGlzIGNoYW5nZWQuCiAgICAgICAgUHJvcGVydHlFdmVudExpc3RlbmVyIHByb3BMaXN0ZW5lciA9IG5ldyBQcm9wZXJ0eUV2ZW50TGlzdGVuZXIoKSB7CiAgICAgICAgICAgIEBPdmVycmlkZQogICAgICAgICAgICBwdWJsaWMgdm9pZCBwcm9wZXJ0eVNldChTdHJpbmcgcHJvcGVydHksIE1hcCBwYXJhbXMpIHsKICAgICAgICAgICAgICAgIGlmICgiYWRtaW4uYXV0aG9yaXplZEpJRHMiLmVxdWFscyhwcm9wZXJ0eSkpIHsKICAgICAgICAgICAgICAgICAgICBBZG1pbk1hbmFnZXIuZ2V0SW5zdGFuY2UoKS5yZWZyZXNoQWRtaW5BY2NvdW50cygpOwogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CgogICAgICAgICAgICBAT3ZlcnJpZGUKICAgICAgICAgICAgcHVibGljIHZvaWQgcHJvcGVydHlEZWxldGVkKFN0cmluZyBwcm9wZXJ0eSwgTWFwIHBhcmFtcykgewogICAgICAgICAgICAgICAgaWYgKCJhZG1pbi5hdXRob3JpemVkSklEcyIuZXF1YWxzKHByb3BlcnR5KSkgewogICAgICAgICAgICAgICAgICAgIEFkbWluTWFuYWdlci5nZXRJbnN0YW5jZSgpLnJlZnJlc2hBZG1pbkFjY291bnRzKCk7CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgIEBPdmVycmlkZQogICAgICAgICAgICBwdWJsaWMgdm9pZCB4bWxQcm9wZXJ0eVNldChTdHJpbmcgcHJvcGVydHksIE1hcCBwYXJhbXMpIHsKICAgICAgICAgICAgICAgIC8vSWdub3JlCiAgICAgICAgICAgIH0KCiAgICAgICAgICAgIEBPdmVycmlkZQogICAgICAgICAgICBwdWJsaWMgdm9pZCB4bWxQcm9wZXJ0eURlbGV0ZWQoU3RyaW5nIHByb3BlcnR5LCBNYXAgcGFyYW1zKSB7CiAgICAgICAgICAgICAgICAvL0lnbm9yZQogICAgICAgICAgICB9CiAgICAgICAgfTsKICAgICAgICBQcm9wZXJ0eUV2ZW50RGlzcGF0Y2hlci5hZGRMaXN0ZW5lcihwcm9wTGlzdGVuZXIpOwoKICAgIH0KCiAgICAvKioKICAgICAqIFRoZSBkZWZhdWx0IHByb3ZpZGVyIHJldHJpZXZlcyB0aGUgY29tbWEgc2VwYXJhdGVkIGxpc3QgZnJvbSB0aGUgc3lzdGVtIHByb3BlcnR5CiAgICAgKiA8dHQ+YWRtaW4uYXV0aG9yaXplZEpJRHM8L3R0PgogICAgICogQHNlZSBvcmcuaml2ZXNvZnR3YXJlLm9wZW5maXJlLmFkbWluLkFkbWluUHJvdmlkZXIjZ2V0QWRtaW5zKCkKICAgICAqLwogICAgQE92ZXJyaWRlCiAgICBwdWJsaWMgTGlzdDxKSUQ+IGdldEFkbWlucygpIHsKICAgICAgICBMaXN0PEpJRD4gYWRtaW5MaXN0ID0gbmV3IEFycmF5TGlzdDw+KCk7CgogICAgICAgIC8vIEFkZCBiYXJlIEpJRHMgb2YgdXNlcnMgdGhhdCBhcmUgYWRtaW5zIChtYXkgaW5jbHVkZSByZW1vdGUgdXNlcnMpLCBwcmltYXJpbHkgdXNlZCB0byBvdmVycmlkZS9hZGQgdG8gbGlzdCBvZiBhZG1pbiB1c2VycwogICAgICAgIFN0cmluZyBqaWRzID0gSml2ZUdsb2JhbHMuZ2V0UHJvcGVydHkoImFkbWluLmF1dGhvcml6ZWRKSURzIik7CiAgICAgICAgamlkcyA9IChqaWRzID09IG51bGwgfHwgamlkcy50cmltKCkubGVuZ3RoKCkgPT0gMCkgPyAiIiA6IGppZHM7CiAgICAgICAgU3RyaW5nVG9rZW5pemVyIHRva2VuaXplciA9IG5ldyBTdHJpbmdUb2tlbml6ZXIoamlkcywgIiwiKTsKICAgICAgICB3aGlsZSAodG9rZW5pemVyLmhhc01vcmVUb2tlbnMoKSkgewogICAgICAgICAgICBTdHJpbmcgamlkID0gdG9rZW5pemVyLm5leHRUb2tlbigpLnRvTG93ZXJDYXNlKCkudHJpbSgpOwogICAgICAgICAgICB0cnkgewogICAgICAgICAgICAgICAgYWRtaW5MaXN0LmFkZChuZXcgSklEKGppZCkpOwogICAgICAgICAgICB9CiAgICAgICAgICAgIGNhdGNoIChJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24gZSkgewogICAgICAgICAgICAgICAgTG9nLndhcm4oIkludmFsaWQgSklEIGZvdW5kIGluIGFkbWluLmF1dGhvcml6ZWRKSURzIHN5c3RlbSBwcm9wZXJ0eTogIiArIGppZCwgZSk7CiAgICAgICAgICAgIH0KICAgICAgICB9CgogICAgICAgIGlmIChhZG1pbkxpc3QuaXNFbXB0eSgpKSB7CiAgICAgICAgICAgIC8vIEFkZCBkZWZhdWx0IGFkbWluIGFjY291bnQgd2hlbiBub25lIHdhcyBzcGVjaWZpZWQKICAgICAgICAgICAgYWRtaW5MaXN0LmFkZChuZXcgSklEKCJhZG1pbiIsIFhNUFBTZXJ2ZXIuZ2V0SW5zdGFuY2UoKS5nZXRTZXJ2ZXJJbmZvKCkuZ2V0WE1QUERvbWFpbigpLCBudWxsLCB0cnVlKSk7CiAgICAgICAgfQoKICAgICAgICByZXR1cm4gYWRtaW5MaXN0OwogICAgfQoKICAgIC8qKgogICAgICogVGhlIGRlZmF1bHQgcHJvdmlkZXIgc2V0cyBhIGNvbW1hIHNlcGFyYXRlZCBsaXN0IGFzIHRoZSBzeXN0ZW0gcHJvcGVydHkKICAgICAqIDx0dD5hZG1pbi5hdXRob3JpemVkSklEczwvdHQ+CiAgICAgKiBAc2VlIG9yZy5qaXZlc29mdHdhcmUub3BlbmZpcmUuYWRtaW4uQWRtaW5Qcm92aWRlciNzZXRBZG1pbnMoamF2YS51dGlsLkxpc3QpCiAgICAgKi8KICAgIEBPdmVycmlkZQogICAgcHVibGljIHZvaWQgc2V0QWRtaW5zKExpc3Q8SklEPiBhZG1pbnMpIHsKICAgICAgICBDb2xsZWN0aW9uPFN0cmluZz4gYWRtaW5MaXN0ID0gbmV3IEFycmF5TGlzdDw+KCk7CiAgICAgICAgZm9yIChKSUQgYWRtaW4gOiBhZG1pbnMpIHsKICAgICAgICAgICAgYWRtaW5MaXN0LmFkZChhZG1pbi50b0JhcmVKSUQoKSk7CiAgICAgICAgfQogICAgICAgIEppdmVHbG9iYWxzLnNldFByb3BlcnR5KCJhZG1pbi5hdXRob3JpemVkSklEcyIsIFN0cmluZ1V0aWxzLmNvbGxlY3Rpb25Ub1N0cmluZyhhZG1pbkxpc3QpKTsKICAgIH0KCiAgICAvKioKICAgICAqIFRoZSBkZWZhdWx0IHByb3ZpZGVyIGlzIG5vdCByZWFkIG9ubHkKICAgICAqIEBzZWUgb3JnLmppdmVzb2Z0d2FyZS5vcGVuZmlyZS5hZG1pbi5BZG1pblByb3ZpZGVyI2lzUmVhZE9ubHkoKQogICAgICovCiAgICBAT3ZlcnJpZGUKICAgIHB1YmxpYyBib29sZWFuIGlzUmVhZE9ubHkoKSB7CiAgICAgICAgcmV0dXJuIGZhbHNlOwogICAgfQoKICAgIC8qKgogICAgICogQ29udmVydHMgdGhlIG9sZCBvcGVuZmlyZS54bWwgc3R5bGUgYWRtaW4gbGlzdCB0byB1c2UgdGhlIG5ldyBwcm92aWRlciBtZWNoYW5pc20uCiAgICAgKi8KICAgIHByaXZhdGUgdm9pZCBjb252ZXJ0WE1MVG9Qcm92aWRlcigpIHsKICAgICAgICBpZiAoSml2ZUdsb2JhbHMuZ2V0WE1MUHJvcGVydHkoImFkbWluLmF1dGhvcml6ZWRKSURzIikgPT0gbnVsbCAmJgogICAgICAgICAgICAgICAgSml2ZUdsb2JhbHMuZ2V0WE1MUHJvcGVydHkoImFkbWluLmF1dGhvcml6ZWRVc2VybmFtZXMiKSA9PSBudWxsICYmCiAgICAgICAgICAgICAgICBKaXZlR2xvYmFscy5nZXRYTUxQcm9wZXJ0eSgiYWRtaW5Db25zb2xlLmF1dGhvcml6ZWRVc2VybmFtZXMiKSA9PSBudWxsKSB7CiAgICAgICAgICAgIC8vIE5vIHNldHRpbmdzIGluIG9wZW5maXJlLnhtbC4KICAgICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KCiAgICAgICAgTGlzdDxKSUQ+IGFkbWluTGlzdCA9IG5ldyBBcnJheUxpc3Q8PigpOwoKICAgICAgICAvLyBBZGQgYmFyZSBKSURzIG9mIHVzZXJzIHRoYXQgYXJlIGFkbWlucyAobWF5IGluY2x1ZGUgcmVtb3RlIHVzZXJzKSwgcHJpbWFyaWx5IHVzZWQgdG8gb3ZlcnJpZGUvYWRkIHRvIGxpc3Qgb2YgYWRtaW4gdXNlcnMKICAgICAgICBTdHJpbmcgamlkcyA9IEppdmVHbG9iYWxzLmdldFhNTFByb3BlcnR5KCJhZG1pbi5hdXRob3JpemVkSklEcyIpOwogICAgICAgIGppZHMgPSAoamlkcyA9PSBudWxsIHx8IGppZHMudHJpbSgpLmxlbmd0aCgpID09IDApID8gIiIgOiBqaWRzOwogICAgICAgIFN0cmluZ1Rva2VuaXplciB0b2tlbml6ZXIgPSBuZXcgU3RyaW5nVG9rZW5pemVyKGppZHMsICIsIik7CiAgICAgICAgd2hpbGUgKHRva2VuaXplci5oYXNNb3JlVG9rZW5zKCkpIHsKICAgICAgICAgICAgU3RyaW5nIGppZCA9IHRva2VuaXplci5uZXh0VG9rZW4oKS50b0xvd2VyQ2FzZSgpLnRyaW0oKTsKICAgICAgICAgICAgdHJ5IHsKICAgICAgICAgICAgICAgIGFkbWluTGlzdC5hZGQobmV3IEpJRChqaWQpKTsKICAgICAgICAgICAgfQogICAgICAgICAgICBjYXRjaCAoSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uIGUpIHsKICAgICAgICAgICAgICAgIExvZy53YXJuKCJJbnZhbGlkIEpJRCBmb3VuZCBpbiBhdXRob3JpemVkSklEcyBhdCBvcGVuZmlyZS54bWw6ICIgKyBqaWQsIGUpOwogICAgICAgICAgICB9CiAgICAgICAgfQoKICAgICAgICAvLyBBZGQgdGhlIEpJRHMgb2YgdGhlIGxvY2FsIHVzZXJzIHRoYXQgYXJlIGFkbWlucywgcHJpbWFyaWx5IHVzZWQgdG8gb3ZlcnJpZGUvYWRkIHRvIGxpc3Qgb2YgYWRtaW4gdXNlcnMKICAgICAgICBTdHJpbmcgdXNlcm5hbWVzID0gSml2ZUdsb2JhbHMuZ2V0WE1MUHJvcGVydHkoImFkbWluLmF1dGhvcml6ZWRVc2VybmFtZXMiKTsKICAgICAgICBpZiAodXNlcm5hbWVzID09IG51bGwpIHsKICAgICAgICAgICAgLy8gRmFsbCBiYWNrIHRvIG9sZCBtZXRob2QgZm9yIGRlZmluaW5nIGFkbWlucyAoaS5lLiB1c2luZyBhZG1pbkNvbnNvbGUgcHJlZml4CiAgICAgICAgICAgIHVzZXJuYW1lcyA9IEppdmVHbG9iYWxzLmdldFhNTFByb3BlcnR5KCJhZG1pbkNvbnNvbGUuYXV0aG9yaXplZFVzZXJuYW1lcyIpOwogICAgICAgIH0KICAgICAgICAvLyBBZGQgZGVmYXVsdCBvZiBhZG1pbiB1c2VyIGlmIG5vIG90aGVyIHVzZXJzIHdlcmUgbGlzdGVkIGFzIGFkbWlucy4KICAgICAgICB1c2VybmFtZXMgPSAodXNlcm5hbWVzID09IG51bGwgfHwgdXNlcm5hbWVzLnRyaW0oKS5sZW5ndGgoKSA9PSAwKSA/IChhZG1pbkxpc3Quc2l6ZSgpID09IDAgPyAiYWRtaW4iIDogIiIpIDogdXNlcm5hbWVzOwogICAgICAgIHRva2VuaXplciA9IG5ldyBTdHJpbmdUb2tlbml6ZXIodXNlcm5hbWVzLCAiLCIpOwogICAgICAgIHdoaWxlICh0b2tlbml6ZXIuaGFzTW9yZVRva2VucygpKSB7CiAgICAgICAgICAgIFN0cmluZyB1c2VybmFtZSA9IHRva2VuaXplci5uZXh0VG9rZW4oKTsKICAgICAgICAgICAgdHJ5IHsKICAgICAgICAgICAgICAgIGFkbWluTGlzdC5hZGQoWE1QUFNlcnZlci5nZXRJbnN0YW5jZSgpLmNyZWF0ZUpJRCh1c2VybmFtZS50b0xvd2VyQ2FzZSgpLnRyaW0oKSwgbnVsbCkpOwogICAgICAgICAgICB9CiAgICAgICAgICAgIGNhdGNoIChJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24gZSkgewogICAgICAgICAgICAgICAgLy8gSWdub3JlIHVzZXJuYW1lcyB0aGF0IHdoZW4gYXBwZW5kZWQgQHNlcnZlci5jb20gcmVzdWx0IGluIGFuIGludmFsaWQgSklECiAgICAgICAgICAgICAgICBMb2cud2FybigiSW52YWxpZCB1c2VybmFtZSBmb3VuZCBpbiBhdXRob3JpemVkVXNlcm5hbWVzIGF0IG9wZW5maXJlLnhtbDogIiArCiAgICAgICAgICAgICAgICAgICAgICAgIHVzZXJuYW1lLCBlKTsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgICAgICBzZXRBZG1pbnMoYWRtaW5MaXN0KTsKCiAgICAgICAgLy8gQ2xlYXIgb3V0IG9sZCBYTUwgcHJvcGVydHkgc2V0dGluZ3MKICAgICAgICBKaXZlR2xvYmFscy5kZWxldGVYTUxQcm9wZXJ0eSgiYWRtaW4uYXV0aG9yaXplZEpJRHMiKTsKICAgICAgICBKaXZlR2xvYmFscy5kZWxldGVYTUxQcm9wZXJ0eSgiYWRtaW4uYXV0aG9yaXplZFVzZXJuYW1lcyIpOwogICAgICAgIEppdmVHbG9iYWxzLmRlbGV0ZVhNTFByb3BlcnR5KCJhZG1pbkNvbnNvbGUuYXV0aG9yaXplZFVzZXJuYW1lcyIpOwogICAgfQoKfQo=",
					"accessTime": 1531708177523,
					"mime": "text/x-java",
					"persission": "rw-r--r--",
					"file": true
				},
				"time": 45
			},
			"/David/openfire_src.orchi/src/java/org/jivesoftware/openfire/admin/AdminManager.java": {
				"status": "error",
				"error": "connection_error",
				"errorMsg": "error de coneccion"
			}
		}
	},
	"downloads": {
		"downloads": {}
	},
	"router": {
		"size": 4,
		"_root": {
			"ownerID": {},
			"entries": [
				["size", 1],
				["_root", {
					"ownerID": {},
					"entries": [
						["location", {
							"pathname": "/SC/unidad",
							"search": "",
							"hash": "#/David/openfire_src.orchi/src/java/org/jivesoftware/openfire",
							"key": "4zij8d"
						}]
					]
				}],
				["__altered", false],
				["location", {
					"pathname": "/SC/unidad",
					"search": "",
					"hash": "#/",
					"key": "fse9c8"
				}]
			]
		},
		"__altered": false,
		"location": {
			"pathname": "/SC/unidad",
			"search": "",
			"hash": "#/David/Clase magistral de proyecto, profe miguel",
			"key": "c193qj"
		}
	}
}